export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  status: "active" | "inactive" | "pending";
  location: string;
  lastActive: string;
  joinDate: string;
  avatar?: string;
}

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@courierlogistics.com",
    role: "admin",
    status: "active",
    location: "New York, NY",
    lastActive: "2 hours ago",
    joinDate: "Jan 15, 2023",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@courierlogistics.com",
    role: "manager",
    status: "active",
    location: "Los Angeles, CA",
    lastActive: "1 day ago",
    joinDate: "Mar 22, 2023",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@courierlogistics.com",
    role: "driver",
    status: "active",
    location: "Chicago, IL",
    lastActive: "30 minutes ago",
    joinDate: "Feb 8, 2023",
  },
  {
    id: "4",
    name: "David Thompson",
    email: "david.thompson@courierlogistics.com",
    role: "dispatcher",
    status: "inactive",
    location: "Houston, TX",
    lastActive: "1 week ago",
    joinDate: "Dec 3, 2022",
  },
  {
    id: "5",
    name: "Lisa Wang",
    email: "lisa.wang@courierlogistics.com",
    role: "customer_service",
    status: "active",
    location: "Phoenix, AZ",
    lastActive: "5 hours ago",
    joinDate: "Apr 17, 2023",
  },
  {
    id: "6",
    name: "James Wilson",
    email: "james.wilson@courierlogistics.com",
    role: "driver",
    status: "pending",
    location: "Philadelphia, PA",
    lastActive: "Never",
    joinDate: "Aug 20, 2024",
  },
  {
    id: "7",
    name: "Maria Garcia",
    email: "maria.garcia@courierlogistics.com",
    role: "manager",
    status: "active",
    location: "San Antonio, TX",
    lastActive: "4 hours ago",
    joinDate: "May 12, 2023",
  },
  {
    id: "8",
    name: "Robert Brown",
    email: "robert.brown@courierlogistics.com",
    role: "driver",
    status: "active",
    location: "San Diego, CA",
    lastActive: "15 minutes ago",
    joinDate: "Jun 30, 2023",
  },
  {
    id: "9",
    name: "Jennifer Davis",
    email: "jennifer.davis@courierlogistics.com",
    role: "dispatcher",
    status: "active",
    location: "Dallas, TX",
    lastActive: "3 hours ago",
    joinDate: "Sep 14, 2023",
  },
  {
    id: "10",
    name: "Christopher Miller",
    email: "christopher.miller@courierlogistics.com",
    role: "customer_service",
    status: "inactive",
    location: "San Jose, CA",
    lastActive: "2 weeks ago",
    joinDate: "Jul 7, 2023",
  },
  {
    id: "11",
    name: "Amanda Taylor",
    email: "amanda.taylor@courierlogistics.com",
    role: "driver",
    status: "active",
    location: "Austin, TX",
    lastActive: "1 hour ago",
    joinDate: "Oct 25, 2023",
  },
  {
    id: "12",
    name: "Kevin Anderson",
    email: "kevin.anderson@courierlogistics.com",
    role: "admin",
    status: "active",
    location: "Jacksonville, FL",
    lastActive: "6 hours ago",
    joinDate: "Nov 8, 2022",
  },
  {
    id: "13",
    name: "Nicole Martinez",
    email: "nicole.martinez@courierlogistics.com",
    role: "manager",
    status: "pending",
    location: "San Francisco, CA",
    lastActive: "Never",
    joinDate: "Aug 15, 2024",
  },
  {
    id: "14",
    name: "Daniel Lee",
    email: "daniel.lee@courierlogistics.com",
    role: "driver",
    status: "active",
    location: "Columbus, OH",
    lastActive: "45 minutes ago",
    joinDate: "Jan 3, 2024",
  },
  {
    id: "15",
    name: "Ashley White",
    email: "ashley.white@courierlogistics.com",
    role: "customer_service",
    status: "active",
    location: "Fort Worth, TX",
    lastActive: "2 hours ago",
    joinDate: "Feb 19, 2024",
  },
  {
    id: "16",
    name: "Ryan Clark",
    email: "ryan.clark@courierlogistics.com",
    role: "dispatcher",
    status: "active",
    location: "Charlotte, NC",
    lastActive: "1 day ago",
    joinDate: "Mar 4, 2024",
  },
  {
    id: "17",
    name: "Stephanie Adams",
    email: "stephanie.adams@courierlogistics.com",
    role: "driver",
    status: "inactive",
    location: "Detroit, MI",
    lastActive: "3 days ago",
    joinDate: "Apr 22, 2024",
  },
  {
    id: "18",
    name: "Brandon Hall",
    email: "brandon.hall@courierlogistics.com",
    role: "manager",
    status: "active",
    location: "El Paso, TX",
    lastActive: "8 hours ago",
    joinDate: "May 16, 2024",
  },
  {
    id: "19",
    name: "Michelle Turner",
    email: "michelle.turner@courierlogistics.com",
    role: "customer_service",
    status: "active",
    location: "Memphis, TN",
    lastActive: "3 hours ago",
    joinDate: "Jun 11, 2024",
  },
  {
    id: "20",
    name: "Jonathan Parker",
    email: "jonathan.parker@courierlogistics.com",
    role: "driver",
    status: "pending",
    location: "Denver, CO",
    lastActive: "Never",
    joinDate: "Aug 5, 2024",
  },
];
